export default [
  {
    id: 1,
    title: "Baptist Curch",
    location: "Hot Springs",
    googleMapsUrl: "https://maps.app.goo.gl/oQN8WGh3P6zubQxL7",
    startDate: "19 June, 2003",
    endDate: "23 June, 2003",
    description:
      "Went to Hot Springs MT's local church to watch my parents get married.",
    imageUrl: "../src/assets/moms-wedding.jpg",
    imgDesc:
      "A photo of my mom, me, and my sister on my moms wedding day dressed up.",
  },
  {
    id: 2,
    title: "Sacajawea Park",
    location: "Bozemen",
    googleMapsUrl: "https://maps.app.goo.gl/PeDjbw4GVLr9Hi7W7",
    startDate: "04 May, 2006",
    endDate: "08 May, 2006",
    description: "Went to the Sacajawea Park in Bozemen MT.",
    imageUrl: "../src/assets/sacajawea.jpg",
    imgDesc:
      "Me and my sister as children standing in front of a bronze Sacajawea statue.",
  },
  {
    id: 3,
    title: "Jack Meets Jasper",
    location: "Home",
    startDate: "04 May, 2012",
    endDate: "04 May, 2012",
    description:
      "The first night Jack and Jasper spent together Jack would follow Jasper everywhere and was so protective of him.",
    imageUrl: "../src/assets/jack-and-jasper.jpg",
    imgDesc:
      "A small white jackrussel named Jack, following a smaller black aphenpincher named Jasper.",
  },
  {
    id: 4,
    title: "Halloween",
    location: "Home",
    startDate: "31 October, 2016",
    endDate: "31 October, 2016",
    description: "Sam and Dad dressed up as dorks and went trick or treating.",
    imageUrl: "../src/assets/halloween-2016.jpg",
    imgDesc:
      "Sam dressed as Kylo Wren and Dad dressed as a star trek character for halloween.",
  },
  {
    id: 5,
    title: "Perkins",
    location: "Missoula",
    googleMapsUrl: "https://maps.app.goo.gl/6CwnWZAxiuh56qNs5",
    startDate: "13 August, 2017",
    endDate: "13 August, 2017",
    description: "Sam gets to order his first big kid meal at Perkins.",
    imageUrl: "../src/assets/sam-and-mom-perkins.jpg",
    imgDesc:
      "Sam pointing at a menu and smiling awkwarly while mom holds the menu.",
  },
  {
    id: 6,
    title: "Study Session",
    location: "Home",
    startDate: "10 April, 2018",
    endDate: "10 April, 2018",
    description: "Jack helping me study.",
    imageUrl: "../src/assets/study-session.jpg",
    imgDesc:
      "A white jackrussle named Jack sleeping on a bed next to an open laptop.",
  },
  {
    id: 7,
    title: "Costa Rica",
    location: "Grecia",
    googleMapsUrl: "https://maps.app.goo.gl/YnkdCdX4tLxDwK8J7",
    startDate: "8 August, 2018",
    endDate: "20 August, 2018",
    description:
      "A trip I took to visit my Nana with my brother Spencer and Mom.",
    imageUrl: "../src/assets/costa-rica.jpg",
    imgDesc: "A picture of a tree filled forset in Grecia, Costa Rica.",
  },
  {
    id: 8,
    title: "The Joy of Running Together",
    location: "Spokane",
    googleMapsUrl: "https://maps.app.goo.gl/kHwuegtWeCUFJCoq8",
    startDate: "13 January, 2019",
    endDate: "14 January, 2019",
    description: "I went to Spokane WA to see something new.",
    imageUrl: "../src/assets/running.jpg",
    imgDesc: "Me pretending to run with the running statues.",
  },
  {
    id: 9,
    title: "Snow Pile",
    location: "Univesity of Montana",
    googleMapsUrl: "https://maps.app.goo.gl/ZSwTgwEzRaMnCf9N8",
    startDate: "26 February, 2019",
    endDate: "26 February, 2019",
    description:
      "My first night studying at the university after coming back to school and the snow is piled up as tall as me.",
    imageUrl: "../src/assets/snow.jpg",
    imgDesc: "Me standing in front of a giant pile of snow.",
  },
  {
    id: 10,
    title: "Sam and Bean Get Along",
    location: "My First Appartment",
    startDate: "28, March, 2019",
    endDate: "28, March, 2019",
    description: "Sam holding Bean close while he makes a sandwich.",
    imageUrl: "../src/assets/sam-and-bean.jpg",
    imgDesc: "Sam holding Bean, the cat, while sitting at a tabel.",
  },
  {
    id: 11,
    title: "Hike with Jasper",
    location: "Rattlesnake Trailhead",
    googleMapsUrl: "https://maps.app.goo.gl/sQkypYwMZJjq1jRq7",
    startDate: "22 April, 2019",
    endDate: "22 April, 2019",
    description:
      "Nothing special happened this hike, but I just love this photo of my boy.",
    imageUrl: "../src/assets/jasper.jpg",
    imgDesc: "Jasper highfiving me while I hold him and smile wide.",
  },
  {
    id: 12,
    title: "The Center of the Universe",
    location: "Wallace",
    googleMapsUrl: "https://maps.app.goo.gl/bfkJyeEwGiNdDYP17",
    startDate: "04 May, 2019",
    endDate: "04 May, 2019",
    description:
      "Wallace is the self proclaimed center of the universe! Since somewhere has to be.",
    imageUrl: "../src/assets/stardust-motel.jpg",
    imgDesc: "Me standing in front of a big sign that says Stardust Motel",
  },
  {
    id: 13,
    title: "Dear Lodge Prison Museum",
    location: "Dear Lodge",
    googleMapsUrl: "https://maps.app.goo.gl/V2xyKLRXEQ7rrasFA",
    startDate: "18 May, 2019",
    endDate: "18 May, 2019",
    description:
      "There's not a lot to do in Montana so we visit old prisons sometimes. People say it's cursed because there was a riot for mistreatment there, I think it's just old.",
    imageUrl: "../src/assets/dearlodge.jpg",
    imgDesc: "A noose used to hang prisoners in old Montana.",
  },
  {
    id: 14,
    title: "Some Garden Roof",
    location: "New York",
    googleMapsUrl: "https://maps.app.goo.gl/cUxtmDni9JS8t3De6",
    startDate: "29 June, 2019",
    endDate: "29 June, 2019",
    description: "It's New York! Them city folk are puting gardens on roofs!!",
    imageUrl: "../src/assets/roof-garden.jpg",
    imgDesc: "A photo taken from a roof showing tall glass buildings.",
  },
  {
    id: 15,
    title: "Turns Out I AM Afraid of Heights",
    location: "World Trade Center",
    googleMapsUrl: "https://maps.app.goo.gl/p3r3kLEBjPrDam6Z6",
    startDate: "26 June, 2019",
    endDate: "26 June, 2019",
    description:
      "We ate dinner up there and it was very expensive. They had one vegitarian option and it was a limabean salad. It was like 20 dollars, in 2019!",
    imageUrl: "../src/assets/word-trade-center.jpg",
    imgDesc: "The view from the Word Trade Center.",
  },
  // {
  //     id: ,
  //     title: "",
  //     location: "",
  //     googleMapsUrl: "",
  //     startDate: "",
  //     endDate: "",
  //     description: "",
  //     imageUrl: "../src/assets/.jpg",
  //     imgDesc: ""
  // },
];
